# Generated by Django 4.2.2 on 2023-06-22 12:31

import django.core.validators
from django.db import migrations, models
import music_app_prep.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=None, max_length=15, validators=[music_app_prep.web.validators.CharAndUnderscoreValidator, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
