# Generated by Django 4.2.2 on 2023-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('pop', 'PopMusic'), ('jazz', 'JazzMusic'), ('rendb', 'R&BMusic'), ('rock', 'RockMusic'), ('country', 'Country Music'), ('dance', 'Dance Music'), ('hiphop', 'Hip Hop Music'), ('other', 'Other')], max_length=30),
        ),
    ]
