# Generated by Django 4.2.2 on 2023-06-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_album_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='profile',
        ),
    ]
