# Generated by Django 4.2.2 on 2023-06-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='Nutrition',
            new_name='nutrition',
        ),
    ]
